import Head from 'next/head';
import Image from 'next/image';
import useSWR from 'swr';

import { fetcher } from 'services';
import styles from '../styles/Home.module.css';

const Home = ({ products }) => {
  const { data } = useSWR(
    [
      `query GetProducts($offset: Int!, $limit: Int!) {
        getProducts(offset: $offset, limit: $limit) {
          name
          image
          categories
        }
      }`,
      {
        offset: 0,
        limit: 20,
      },
    ],
    fetcher,
    { initialData: products },
  );

  console.log({ data });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <pre>{JSON.stringify(data, null, 2)}</pre> */}

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};


export const getServerSideProps = async () => {
  const data = await fetcher(
    `query GetProducts($offset: Int!, $limit: Int!) {
        getProducts(offset: $offset, limit: $limit) {
          name
          image
          categories
        }
    }`,
    {
      offset: 0,
      limit: 20,
    },
  );

  if (!data) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      products: data,
    },
  };
};

export default Home;

